apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: welcome-banner
spec:
  backgroundColor: '#EE0000'
  color: '#fff'
  link:
    href: https://docs.openshift.com/container-platform/4.12
    text: (Event Information)
  location: BannerTop
  text: Welcome to OpenShift
